_BASE_: maskformer2_R50_bs16_50ep.yaml
MODEL:
  WEIGHTS: "R-101.pkl"
  SEM_SEG_HEAD:
    # PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    PIXEL_DECODER_NAME: "FreqAwareMSDeformAttnPixelDecoder2"
  RESNETS:
    # USE_CHECKPOINT: True ####
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
